<head>
<style>



footer{
	background-color: #00111a;
	padding-left: 20px;
	padding-right: 20px;
	padding-bottom: 20px;
	padding-top: 30px;
}

footer h2{
	color: white;
	text-align: center;
}
footer .about{
	color: white;
}

footer .me{
	color: white;
	text-align: center;
	font-size: 20px;
	
}

footer a.top {
	margin: auto;
	display: block;
	color: black;
	background-color: white;
	text-align: center;
	padding: 5px;
	text-decoration: none;
	background-position: relative;
	width: 10%;
}

footer a:hover {
	background-color:grey;
	color: white;
	padding: 5px 5px;
}

</style>
</head>


  
<footer class="footer">
<a class="top" href="#imgtop">To the Top</a>
<h2>About</h2>
<div class="about" id="about1">
“Tourist Guide” is the Online Tourism Information System which provides information about Mumbai Tourism. Tourism is commonly referred as to travel to another location within the same country or internationally. The purpose and motivation to become a tourist are to meet new people, rest, relaxation, and experience other cultures, or simply to do something and have an adventure. The main thing about Mumbai tourism that attracts tourists are its different cultures, history, beaches, forts and food. Tourism is vital for all countries, due to the income generated by the consumption of goods and services by tourists, the taxes levied on businesses in the tourism industry, and opportunity for employment and economic advancement by working in the industry. 
Due to the Mumbai’s rich history, its culture and diversity, makes it international tourism. I present Tourist Guide for Mumbai tourism which helps tourist to find best places to visit in Mumbai along with what’s best to eat, shopping in Mumbai, Hotels available , safety rules, packages in Mumbai via my website. 
</div>
<br /><br />
<div class="me">
By Manjushree
</div>


</footer>